nominal changes for assets screen
Tonomy-Foundation/Tonomy-ID pull request #1273
Opened 2024-11-28 19:56 UTC by sadiabbasi

2024-11-28 20:01 UTC, theblockstalk commented on src/containers/AssetsContainer.tsx
> +        fetchCryptoAssets().then(() => setAssetLoading(false));
this will cause fetchCryptoAssets to be called on render, but not to update balances... why is this better...

2024-11-28 20:03 UTC, sadiabbasi commented on src/containers/AssetsContainer.tsx
> +        fetchCryptoAssets().then(() => setAssetLoading(false));
this will call fetchCryptoAssets  on render ... and then also call after updateBalance in line 100..

before it fetchCryptoAssets call after updateBalance on render and first time user open screen update balance throw error because first render fetchAsset call after updateBalance..

2024-11-29 08:59 UTC, theblockstalk commented on src/containers/AssetsContainer.tsx
> +            if (!accountsInitialized) {
- move this check into `updateAllBalances()`, before `updateBalance()` is called
- remove `updateBalance()` from this if condition

2024-11-29 14:28 UTC, theblockstalk requested changes

2024-11-29 14:28 UTC, theblockstalk commented on package.json
> +        "@tonomy/tonomy-id-sdk": "0.24.0-rc.1",
change to latest version 0.24. the `-rc.` is a previous version.

2024-11-29 21:09 UTC, merged

2024-12-04 12:52 UTC, theblockstalk commented
:tada: This PR is included in version 0.141.0-development.1 :tada:

The release is available on [GitHub release](https://github.com/Tonomy-Foundation/Tonomy-ID/releases/tag/0.141.0-development.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-12-04 19:29 UTC, theblockstalk commented
:tada: This PR is included in version 0.141.0 :tada:

The release is available on [GitHub release](https://github.com/Tonomy-Foundation/Tonomy-ID/releases/tag/0.141.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: