user registration process
Tonomy-Foundation/Tonomy-ID pull request #466
Opened 2023-02-10 14:06 UTC by HaseebUllahAbbasi

user Registration process with cases defined in issue

2023-02-14 09:39 UTC, Rebal67 requested changes
please check the DOD of this task, this is definitely not finished

2023-02-14 09:39 UTC, Rebal67 commented on src/store/userStore.ts
> +type statusData = 'isLoggedIn' | 'creatingAccount' | 'NotLoggedIn' | 'LoggingIn';
lets move this to enum for faster value changes

2023-02-14 09:39 UTC, Rebal67 commented on src/store/userStore.ts
> +    updateBiometric: (pin) => void;
isn't status and get status doing the same thing ?

2023-02-14 09:39 UTC, Rebal67 commented on src/store/userStore.ts
> +    },
why are you spreading the state what will this do?
you can just use set({hasCompletedBiometric: true })

2023-02-14 09:39 UTC, Rebal67 commented on src/store/userStore.ts
> +    },
i am not seeing presistant storage here not the ability to set the flags on false

2023-02-14 09:39 UTC, Rebal67 commented on src/containers/LoginPasswordContainer.tsx
> +                        password: password,
can you use block for the if statement here

2023-02-14 09:39 UTC, Rebal67 commented on src/containers/LoginPasswordContainer.tsx
> +                        password: password,
shouldnt status be updated here to user is loggedin

2023-02-21 12:50 UTC, theblockstalk commented on src/store/userStore.ts
> +    hasCompletedPin: boolean;
hasCompletedPin and hasCompletedBiometric are not implemented. remove

2023-02-21 12:51 UTC, theblockstalk commented on src/store/userStore.ts
> +    checkPin: () => boolean;
checkPin rename getPin
checkBiometric rename getBiometric

updatePin and Biometric do the same thing logical as setPin and Biometric, they can be removed

2023-02-21 12:54 UTC, theblockstalk commented on src/containers/PinScreenContainer.tsx
> +                        await store.removeFlags();
remove flags should be at the end of biometrics I think

2023-02-21 12:55 UTC, theblockstalk commented on src/containers/PinScreenContainer.tsx
> +                    if (!(await store.checkBiometric())) {
this is never true, they have never finished Biometric before PIN

2023-02-21 12:56 UTC, theblockstalk commented on src/containers/LoginPasswordContainer.tsx
> +                if (!(await store.checkBiometric())) {
user always navigated to PIN after they login

2023-02-21 12:56 UTC, theblockstalk commented on src/containers/LoginPasswordContainer.tsx
> +                if (!(await store.checkBiometric())) {
no need to check Biometric or Pin here

2023-02-21 13:08 UTC, HaseebUllahAbbasi commented on src/store/userStore.ts
> +// type UserStats ={
sure

2023-02-21 13:09 UTC, HaseebUllahAbbasi commented on src/store/userStore.ts
> +        await set().user.logout();
yeah it is get

2023-02-21 13:09 UTC, HaseebUllahAbbasi commented on src/store/userStore.ts
> +    hasCompletedPin: boolean;
removing

2023-02-21 13:10 UTC, HaseebUllahAbbasi commented on src/store/userStore.ts
> +    checkPin: () => boolean;
sure

2023-03-06 10:08 UTC, HaseebUllahAbbasi commented on src/containers/LoginPasswordContainer.tsx
> +                if (!(await store.checkBiometric())) {
removed

2023-03-06 11:08 UTC, closed without merging