face id for ios started
Tonomy-Foundation/Tonomy-ID pull request #507
Opened 2023-02-17 11:55 UTC by HaseebUllahAbbasi

UI implemented for Face Id and conditional navigation based on device

2023-02-27 14:06 UTC, theblockstalk requested changes

2023-02-27 14:06 UTC, theblockstalk commented on src/containers/FaceIDUpdateContainer.tsx
> +            console.log('face Id to be detected on ios and updated on block chain');
1. here we should be using `LocalAuthenticator` to show the prompts.
2. I thought we discussed that this work would be integrated with the `FingerprintUpdateContainer`?

2023-02-27 14:06 UTC, theblockstalk commented on src/containers/FaceIDUpdateContainer.tsx
> +        navigation.navigate('Drawer');
this will need to be updated after you rebase to use the new navigation with state. onSkil also needs to call
```
user.saveLocal()
user.updateKeys()
```
see above comment. The `FingerprintUpdateContainer` already has this logic

2023-02-27 14:15 UTC, theblockstalk commented on src/containers/FaceIDUpdateContainer.tsx
> +import React, { useState } from 'react';
delete this file and the FaceIDUpdateScreen

2023-03-01 08:30 UTC, HaseebUllahAbbasi commented on src/containers/FaceIDUpdateContainer.tsx
> +import React, { useState } from 'react';
@theblockstalk  yeah, its deleted

2023-03-01 08:55 UTC, HaseebUllahAbbasi commented on src/containers/FaceIDUpdateContainer.tsx
> +        navigation.navigate('Drawer');
@theblockstalk that is completed already done in 517 in bug fix

2023-03-02 14:57 UTC, theblockstalk commented on src/containers/FingerprintUpdateContainer.tsx
> +                    await updateKeys();
also in the `onSkipp()` function

2023-03-02 14:58 UTC, theblockstalk commented on src/components/TModal.tsx
> +    linkOnPress: () => void;
it looks like this should be optional

2023-03-02 15:20 UTC, HaseebUllahAbbasi commented on src/components/TModal.tsx
> +    linkOnPress: () => void;
yeah, the linkOnPress should be optional @theblockstalk

2023-03-02 15:21 UTC, HaseebUllahAbbasi commented on src/containers/FingerprintUpdateContainer.tsx
> +            const isSupported = await LocalAuthentication.hasHardwareAsync();
yeah got it @theblockstalk  implementing

2023-03-03 09:44 UTC, HaseebUllahAbbasi commented on src/navigation/Root.tsx
> +import { Platform } from 'react-native';
removed

2023-03-03 09:47 UTC, HaseebUllahAbbasi commented on src/containers/FingerprintUpdateContainer.tsx
> +                    await updateKeys();
that is called         await user.updateKeys(password);
 with navigation

2023-03-03 12:59 UTC, Rebal67 commented on src/containers/FingerprintUpdateContainer.tsx
>              }
this only changes the model state but doesnt open the model

2023-03-03 13:08 UTC, HaseebUllahAbbasi commented on src/containers/FingerprintUpdateContainer.tsx
>              }
update

2023-03-04 10:12 UTC, theblockstalk approved these changes

2023-03-04 17:40 UTC, merged