change pin ui
Tonomy-Foundation/Tonomy-ID pull request #569
Opened 2023-03-10 14:36 UTC by HaseebUllahAbbasi

change pin ui

2023-03-16 12:20 UTC, theblockstalk requested changes

2023-03-16 12:20 UTC, theblockstalk commented on src/navigation/Drawer.tsx
> +            {/* <Drawer.Screen name="ChangePin" options={{ title: 'Change Pin' }} component={ChangePinScreen} /> */}
please remove comments

2023-03-16 12:20 UTC, theblockstalk commented on src/containers/SettingsContainer.tsx
> +                            navigation.navigate('ChangePin');
this is not the design. Design is to go to the next screen
https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=3336-14957&t=jiCU22LaFu4xgrFQ-4

Its acceptable for now

2023-03-16 12:34 UTC, HaseebUllahAbbasi commented on src/containers/ChangePinScreenContainer.tsx
> +export default function ChangePinScreenContainer({ navigation }: { navigation: Props['navigation'] }) {
sure making

2023-03-16 12:39 UTC, HaseebUllahAbbasi commented on src/containers/SettingsContainer.tsx
> +                            navigation.navigate('ChangePin');
@theblockstalk 
the 558 and 548 are different task, the #558 is about changing screens where as the #548 is about adding options screen  
the ui you have mentioned above is in #548

2023-03-17 15:43 UTC, Rebal67 commented on src/navigation/Drawer.tsx
> +
why change pin is added to the drawer ?

2023-03-20 11:49 UTC, HaseebUllahAbbasi commented on src/navigation/Drawer.tsx
> +            {/* <Drawer.Screen name="ChangePin" options={{ title: 'Change Pin' }} component={ChangePinScreen} /> */}
removed

2023-03-20 11:51 UTC, HaseebUllahAbbasi commented on src/navigation/Drawer.tsx
> +
it will be merged with 548 later so first 548 is merged with dev then after rebase i will complete its routing,
and these routes will be removed

2023-03-20 11:56 UTC, HaseebUllahAbbasi commented
> the task is about making the UI of the PIN UI looks the same. the text isnt the same in 2 pages (when creating account vs login) and there isn't a text when changing a UI plus the buttons aren't like the figma design

the buttons are with border radius and has content and actions according to the conditional rendering , @Rebal67  could you please specify what am i missing , Thanks

2023-03-21 11:07 UTC, HaseebUllahAbbasi commented
![Screenshot_2023-03-21-16-06-45-375_foundation.tonomy.projects.tonomyiddevelopment.jpg](https://user-images.githubusercontent.com/53255366/226588521-fe33fd86-5ff2-401b-ad07-a936d5806cc4.jpg)

![Screenshot_2023-03-21-16-06-51-118_foundation.tonomy.projects.tonomyiddevelopment.jpg](https://user-images.githubusercontent.com/53255366/226588522-c66247f5-7d1c-415d-8c17-edafee042419.jpg)

![Uploading Screenshot_2023-03-21-16-06-38-631_foundation.tonomy.projects.tonomyiddevelopment.jpg …]()

![Screenshot_2023-03-21-16-06-56-447_foundation.tonomy.projects.tonomyiddevelopment.jpg](https://user-images.githubusercontent.com/53255366/226588523-f8899d85-14bf-4eb3-b750-41971504327f.jpg)

![Screenshot_2023-03-21-16-06-35-897_foundation.tonomy.projects.tonomyiddevelopment.jpg](https://user-images.githubusercontent.com/53255366/226588520-655be2b0-e364-4002-a5a1-9dcd8191feb4.jpg)

2023-03-22 11:25 UTC, Rebal67 approved these changes

2023-03-24 08:27 UTC, merged